sudo: false
language: python
python:
  - "3.5"


install:
  - sudo apt-get install python3-pip
  - pip3 install pytest-cov==2.4.0
  - pip3 install coveralls==1.1
  
script:
  - python3 setup.py install
  - coverage run --source=konlp -m py.test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - hyun02.engineer@gmail.com
    on_success: never
    on_failure: always
